# Generated by Django 4.1.3 on 2024-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('desc', models.CharField(max_length=122)),
                ('img', models.FileField(max_length=122, upload_to='')),
            ],
        ),
    ]
