# Generated by Django 4.1.3 on 2024-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=122)),
                ('item_desc', models.CharField(max_length=122)),
                ('item_price', models.IntegerField()),
                ('item_image', models.FileField(max_length=122, upload_to='')),
            ],
        ),
    ]
